<a href="https://colab.research.google.com/github/1phalleyscomet/2025-1/blob/main/OpenCV_imageprocessing_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#관심영역 지정 코드
roi=img[y:y+h,x:x+w] #슬라이싱

In [ ]:
import cv2
import numpy as np

img=cv2.imread("../img/sunset.jpg")

x=320; y=150; w=50; h=50 #roi좌표
roi=img[y:y+h,x:x+w] #roi 지정
print(roi.shape) #roi shape,(50,50,3)
cv2.rectangle(roi,(0,0),(h-1,w-1),(0,255,0)) #roi에 사각형 그리기
#관심영역 지정 X시
#cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#관심영역만 새 창 표시
import cv2
import numpy as np

img=cv2.imread("../img/sunset.jpg")

x=320; y=150; w=50; h=50 #roi좌표
roi=img[y:y+h,x:x+w] #roi 지정
img2=roi.copy()#roi 배열 복제
img[y:y+h,x+w:x+w+w]=roi #새로운 좌표에 roi추가, 태양 2개 생성
cv2.rectangle(img,(x,y),(x+w+w,y+h),(0,255,0))

cv2.imshow("img",img) #원본 이미지 출력
cv2.imshow("roi",img2) #roi만 따로 출력
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#마우스로 관심영역 지정
import cv2
import numpy as np

isDragging=False #마우스 드래그 상태 저장
x0,y0,w,h =-1=-1=-1=-1 #영역 선택 좌표 저장
blue,red=(255,0,0),(0,0,255)

def onMouse(event,x,y,flags,param): #마우스 이벤트 핸들 함수
    global isDragging,x0,y0,img #전역변수 참조
    if event==cv2.EVENT_LBUTTONDOWN: #마우스 왼쪽 버튼 누름
        isDragging=True
        x0=x
        y0=y
    elif event==cv2.EVENT_MOUSEMOVE: #마우스 움직임
        if isDragging: #마우스 드래그 진행 중
            img_draw=img.copy() #사각형 그림 표현을 위한 이미지 복제
            cv2.rectangle(img_draw,(x0,y0),(x,y),blue,2) #드래그 진행 영역 표시
            cv2.imshow('img',img_draw)
        elif event == cv2.EVENT_LBUTTONUP
            if isDragging =False
            w=x-x0
            h=y-y0
            print("x:%d","y:%d","w:%d","h:%d" % (x0,y0,w,h))
            if w>0 and h>0:
                img_draw=img.copy()
                cv2.rectangle(img_draw,(x0,y0),(x,y),red,2)
                cv2.imshow('img',img_draw)
                roi=img[y0:y0+h,x0:x0+w]
                cv2.imshow('cropped',roi)
                cv2.moveWindow('cropped',0,0)
                cv2.imwrite('./cropped.jpg',roi)
                print("cropped.")
            else:
                cv.imshow('img',img)
                print("좌측상단에서 우측 하단으로 드래그하세요."
img=cv2.imread("../img/sunset.jpg")
cv2.imshow('img',img)
cv2.setMoutseCallback('img',onMouse)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
#opencv 3 selectROI
import cv2
import numpy as np

img=cv2.imread("../img/sunset.jpg")
x,y,h,w=cv2.selectROI('img',img,False)
if w and h:
    roi=img[y:y+h,x:x+w]
    cv2.imshow('cropped',roi)
    cv2.moveWindow('cropped',0,0)
    cv2.imwrite('./cropped2.jpg',roi)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

img=cv2.imread('../img/opencv_logo.png')
bgr=cv2.imread('../img/opencv_logo.png',cv2.IMREAD_COLOR)
bgra=cv2.imread('../img/opencv_logo.png',cv2.IMREAD_UNCHANGED)
print("default:",img.shape,'color:',bgr.shape,'unchanged:',bgra.shape)
cv2.imshow('bgr',bgr)
cv2.imshow('bgra',bgra)
cv2.imshow('alpha',bgra[:,:,3])

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

img=cv2.imread('../img/girl.png')
img2=img.astype(np.unit16) #dtype변경
b,g,r=cv2.split(img2)#채널별로 분리
gray1=((b+g+r)/3.astype(np.uint8)#평균값 연산 후 dtype변경
gray2=cv2.cvtColor(img,cv2,COLOR_BGR2GRAY) #BGR을 그레이 스케일로 변경
cv2.imshow('original',img)
cv2.imshow('gray1',gray1)
cv2.imshow('gray2',gray2)

cv2.waitKey(0)
cv2.destroyAllWindow()

In [ ]:
#플래그 상수 출력
[i for i in dir(cv2) if i.startswith('COLOR_')]

In [ ]:
#BGR->HSV
import cv2
import numpy as np

red_bgr=np.array([[[0,0,255]]],dype=np.uint8) #red값만 갖는 픽셀
green_bgr=np.array([[[0,255,0]]],dype=np.uint8) #green값만 갖는 픽셀
blue_bgr=np.array([[[255,0,0]]],dype=np.uint8) #blue값만 갖는 픽셀
yellow_bgr=np.array([[[0,225,255]]],dype=np.uint8) #yellow값만 갖는 픽셀

red_hsv=cv2.cvtColor(red_bgr,cv2.COLOR_BGR2HSV);
green_hsv=cv2.cvtColor(green_bgr,cv2.COLOR_BGR2HSV);
blue_hsv=cv2.cvtColor(blue_bgr,cv2.COLOR_BGR2HSV);
yellow_hsv=cv2.cvtColor(yellow_bgr,cv2.COLOR_BGR2HSV);

print('red:',red_hsv)
print('green:',green_hsv)
print('blue:',blue_hsv)
print('yellow:',yellow_hsv)

In [ ]:
#전역 스레시홀딩
import cv2
import numpy as np
import matplotlib.pyplot as plt

img=cv2.imread('../img/gray_gradient.png',cv2.IMREAD_GRAYSCALE)

#NUMPY연산으로 바이너리 이미지 생성
thresh_np=np.zeros_like(img) #원본과 동일한 크기의 0으로 채워진 이미지
thresh_np[img>127]=255 #127보다 큰 값만 255로 변경

#opencv함수로 바이너리 이미지 생성
ret,thresh_cv=cv2.threshold(img,127,255,cv2.THRESH_BINARY)
print(ret) #127.0 바이너리 이미지에 사용된 경계 값 변환

#원본, 결과물 출력
img={'origial':img,'numpy':thresh_np,'opencv':thresh_cv}
for i, (key,value) in enumerate(img.items()):
    plt.subplot(1,3,i+1)
    plt.title(key)
    plt.imshow(value,cmap='gray')
    plt.xticks([]); plt.ythicks([])

In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img=cv2.imread('../img/gray_gradient.png',cv2.IMREAD_GRAYSCALE)

_,t_bin=cv2.threshold(img,127,255,cv2.THRESH_BINARY) #127보다 크면 255
_,t_bininv=cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)
_,t_trunc=cv2.threshold(img,127,255,cv2.THRESH_TRUNC)
_,t_2zr=cv2.threshold(img,127,255,cv2.THRESH_TOZERO)
_,t_2zrinv=cv2.threshold(img,127,255,cv2.THRESH_TOZERO_INV)

img={'original':img,'binary':t_bin,'binary_inv':t_bininv,'trunc':t_trunc,'tozero':t_2zr,'tozero_inv':t_2zrinv}
for i, (key,value) in enumerate(img.items()):
    plt.subplot(2,3,i+1)
    plt.title(key)
    plt.imshow(value,cmap='gray')
    plt.xticks([]); plt.yticks([]) #축 눈금 숨기기

plt.show()

In [ ]:
#오츠의 알고리즘을 적용한 스레시홀드
import cv2
import numpy as np
import matplotlib.pyplot as plt

img=cv2.imread('../img/scaned_paper.png',cv2.IMREAD_GRAYSCALE)
#경계값을 130으로 지정
_,t_130=cv2.threshold(img,130,225,cv2.cv2.THRESH_BINARY)
#오츠의 알고리즘 선택
t,t_otsu=cv2.cv2.threshold(img,-1,255,cv2.THRESH_BINARY|cv2.THRESH_OTSU)
print('otsu threshold:',t)

imgs={'original':img,'t:130':t_130,'otsu:%d':%t:t_otsu}
for i, (key,value) in enumerate(imgs.items()):
    plt.subplot(1,3,i+1)
    plt.title(key)
    plt.imshow(value,cmap='gray')
    plt.xticks([]); plt.yticks([])
plt.show()

In [ ]:
#적응형 스레시홀드
import cv2
import numpy as np
import matplotlib.pyplot as plt

blk_size=9 #블록 사이즈
C=5 #차감상수
img=cv2.imread('../img/sudoku.png',cv2.cv2.IMREAD_GRAYSCALE)

ret, th1=cv2.threshold(img,0,255,cv2.cv2.THRESH_BINARY|cv2.THRESH_OTSU)
th2=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,blk_size,C)
TH3=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,blk_size,C)

IMGS={'original':img,'global-otsu:%d'%ret:th1,'adapted-mean':th2,'adapted-gaussian':th3}
for i, (key,value) in enumerate(imgs.items()):
    plt.subplot(1,3,i+1)
    plt.title(key)
    plt.imshow(value,cmap='gray')
    plt.xticks([]); plt.yticks([])
plt.show()

In [ ]:
#영상의 사칙연산
import cv2
import numpy as np

a=np.uint8([[200,50]])
b=np.uint8([[100,100]]) #연산에 사용할 배열

#numpy배열 직접 연산
add1=a+b
sub1=a-b
mult1=a*2
div1=a/3

#opencv api 연산
add2=cv2.add(a,b)
sub2=cv2.subtract(a,b)
mult2=cv2.multiply(a,2)
div2=cv2.divide(a,3)

print(add1,add2)
print(sub1,sub2)
print(mult1,mult2)
print(div1,div2)


[[ 44 150]] [[255 150]]
[[100 206]] [[100   0]]
[[144 100]] [[255 100]]
[[66.66666667 16.66666667]] [[67 17]]


In [ ]:
#mask와 누적 할당
import cv2
import numpy as np

a=np.array([[1,2]],dtype=np.uint8)
b=np.array([[10,20]],dtype=np.uint8)
mask=np.array([[1,0]],dtype=np.uint8)

c1=cv2.add(a,b,None,mask)
print(c1)
c2=cv2.add(a,b,b,mask)
print(c2)
print(b)
print(a)

[[11  0]]
[[11 20]]
[[11 20]]
[[1 2]]


In [ ]:
#이미지 단순 합성
import cv2
import numpy as np
import matplotlib.pylab as plt

img1=cv2.imread('../img/wing_wall.jpg')
img2=cv2.imread('../img/yate.jpg')

img3=img1+img2
img4=cv2.add(img1,img2)

imgs={'img1':img1,'img2':img2,'img1+img2':img3,'cv2.add(img1,img2)':img4}

for i (k,v) in enumerate(imgs.items()):
    plt.subplot(2,2,i+1)
    plt.imshow(v[:,:,::-1])
    plt.title(k)
    plt.xticks([]);plt.yticks([])
plt.show()

In [ ]:
#50% 알파 블랜딩
import cv2
import numpy as np

alpha=0.5
img1=cv2.imread('../img/wing_wall.jpg')
img2=cv2.imread('../img/yate.jpg')

#직접 연산
blended=img1*alpha+img2*(1-alpha)
blended=blended.astype(np.uint8)
cv2.imshow("img1*alpha+img2*(1-alpha)",blended)

#opencv api
blended=cv2.addWeighted(img1,alpha,img2,(1-alpha),0)
cv2.imshow("cv2.addWeighted",blended)


In [ ]:
#트랙바로 알파값 조절
import cv2
import numpy as np

win_name='alpha blending'
trackbar_name='fade'

def onChange(x):
    alpha=x/100
    dst=cv2.addWeighted(img1,1-alpha,img2,alpha,0)
    cv2.imshow(win_name,dst)

img1=cv2.imread('../img/wing_wall.jpg')
img2=cv2.imread('../img/yate.jpg')

cv2.imshow(win_name,img1)
cv2.createTrackbar(trackbar_name,win_name,0,100,onChange)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#bitwise
import cv2
import numpy as np
import matplotlib.pylab as plt

img1=np.zeros((200,400),dtype=np.uint8)
img2=np.zeros((200,400),dtype=np.uint8)

img1[:, :200]=255
img2[100:200, : ]=255

bitAnd=cv2.bitwise_and(img1,img2)
bitOr=cv2.bitwise_or(img1,img2)
bitXor=cv2.bitwise_xor(img1,img2)
bitNot=cv2.bitwise_not(img1)

imgs={'img1':img1,'img2':img2,'bitAnd':bitAnd,'bitOr':bitOr,'bitXor':bitXor,'not(img1)':bitNot}
for i (title,img) in enumerate(imgs.items()):
    plt.subplot(2,3,i+1)
    plt.imshow(img,cmap='gray')
    plt.title(title)
    plt.xticks([]); plt.yticks([])
plt.show()

In [ ]:
#마스킹
import cv2
import numpy as np
import matplotlib.pylab as plt

img=cv2.imread('../img/girl.jpg')

mask=np.zeros_like(img)
cv2.circle(mask,(150,140),100,(255,255,255),-1)

masked=cv2.bitwise_and(img,mask)

cv2.imshow('img',img)
cv2.imshow('mask',mask)
cv2.imshow('masked',masked)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#차영상
import cv2
import numpy as np

img1=cv2.imread('../img/robot_arm1.jpg')
img2=cv2.imread('../img/robot_arm2.jpg')
img1_gray=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
img2_gray=cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
diff=cv2.absdiff(img1_gray,img2_gray)
#차영상을 극대화하기 위한 스레시 홀드 처리 및 컬러로 변환
_,diff_bin=cv2.threshold(diff,30,255,cv2.THRESH_BINARY)
diff_red=cv2.cvtColor(diff,cv2.COLOR_GRAY2BGR)
diff_red[:,:,2]=0

spot=cv2.bitwise_xor(img2,diff_red)

cv2.imshow('img1',img1)
cv2.imshow('img2',img2)
cv2.imshow('diff',diff)
cv2.imshow('spot',spot)


In [ ]:
#투명배경png파일을 이용한 합성
import cv2
import numpy as np

img_fg=cv2.imread('../img/opencv_logo.png',cv2.IMREAD_UNCHANGED)
img_bg=cv2.imread('../img/girl.jpg')

_, mask=cv2.threshold(img_fg[:,:,3],1,255,cv2.THRESH_BYNARY)
mask_inv=cv2.bitwise_not(mask)

#전경 영상 크기로 배경 영상에서 roi잘라내기
img_fg=cv2.cvtColor(img_fg,cv2.COLOR_BGRA2BGR)
h,w=img_fg.shape[:2]
roi=img_bg[10:10+h,10:10+w]

#마스크를 이용해서 오려내기
masked_fg=cv2.bitwise_and(img_fg,img_fg,mask=mask)
masked_bg=cv2.bitwise_and(roi,roi,mask=mask_inv)

added=masked_fg+masked_bg
img_bg[10:10+h,10:10+w]=added

cv2.imshow('mask',mask)
cv2.imshow('mask_inv',mask_inv)
cv2.imshow('masked_fg',mask_fg)
cv2.imshow('masked_bg',masked_bg)
cv2.imshow('added',added)
cv2.imshow('result',img_bg)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
 #hsv색상으로 마스킹
import cv2
import numpy as np
import matplotlib.pylab as plt

img=cv2.imread('../img/cube.jpg')
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

#영역 지정
blue1=np.array([90,50,50])
blue2=np.array([120,255,255])
green1=np.array([45,50,50])
green2=np.array([75,255,255])
red1=np.array([0,50,50])
red2=np.array([15,255,255])
red3=np.array([165,50,50])
red4=np.array([180,255,255])
yellow1=np.array([20,50,50])
yellow2=np.array([35,255,255])

#마스크 생성
mask_blue=cv2.inRange(hsv,blue1,blue2)
mask_green=cv2.inRange(hsv,green1,green2)
mask_red=cv2.inRange(hsv,red1,red2)
mask_red2=cv2.inRange(hsv,red3,red4)
mask_yellow=cv2.inRange(hsv,yellow1,yellow2)

#색상 추출
res_blue=cv2.bitwise_and(img,img,mask=mask_blue)
res_green=cv2.bitwise_and(img,img,mask=mask_green)
res_red1=cv2.bitwise_and(img,img,mask=mask_red)
res_red2=cv2.bitwise_and(img,img,mask=mask_red2)
res_red=cv2.bitwise_or(res_red1,res_red2)
res_yellow=cv2.bitwise_and(img,img,mask=mask_yellow)

#출력
imgs={'original':img,'blue':res_blue,'green':res_green,'red':res_red,'yellow':res_yellow}

for i, (key,value) in enumerate(imgs.items()):
    plt.subplot(2,3,i+1)
    plt.title(key)
    plt.imshow(value[:,:,::-1])
    plt.xticks([]); plt.yticks([])
plt.show()

In [ ]:
#chroma key
import cv2
import numpy as np
import matplotlib.pylab as plt

img=cv2.imread('../img/man_chromakey.jpg')
img2=cv2.imread('../img/street.jpg')

#roi선택을 위한 좌표 계산
height1,width1=img1.shape[:2]
height2,width2=img2.shape[:2]
x=(width2-width1)//2
y=height2-height1
w=x+width1
h=y+height1

chromakey=img[:10,:10,:]
offset=20

hsv_chroma=cv2.cvtColor(chromakey,cv2.COLOR_BGR2HSV)
hsv_img=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

chroma_h=hsv_chroma[:,:,0]
lower=np.array([chroma_h.min()-offset,100,100])
upper=np.array([chroma_h.max()+offset,255,255])

mask=cv2.inRange(hsv_img,lower,upper)
mask_inv=cv2.bitwise_not(mask)
roi=img2[y:h,x:w]
fg=cv2.bitwise_and(hsv_img,lower,upper)
bg=cv2.bitwise_and(roi,roi,mask=mask)
img2[y:h,x:w]=fg+bg

cv2.imshow('chromakey',img1)
cv2.imshow('added',img2)
cv2

In [ ]:
#seamlessclone 합성
import cv2
import numpy as np
import matplotlib.pylab as plt

img1=cv2.imread('../img/drawing.jpg')
img2=cv2.imread('../img/hand.jpg')

mask=np.full_like(img1,255)

height,width=img2.shape[:2]
center=(width//2,height//2)

normal=cv2.seamlessClone(img1,img2,mask,center,cv2.NORMAL_CLONE)
cv2.imshow('normal',normal)
mixed=cv2.seamlessClone(img1,img2,mask,center,cv2.MIXED_CLONE)
cv2.imshow('mixed',mixed)